# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

import cv2
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QLabel, QFileDialog


class Ui_title(QtWidgets.QMainWindow):
    def setupUi(self, title):
        super(Ui_title, self).__init__()
        title.setObjectName("title")
        title.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(title)
        title.setCentralWidget(self.centralwidget)
        self.centralwidget.setObjectName("centralwidget")

        self.shipinzhanshi = QtWidgets.QLabel(self.centralwidget)
        self.shipinzhanshi.setGeometry(QtCore.QRect(100, 110, 591, 301))
        self.shipinzhanshi.setText("")
        self.shipinzhanshi.setObjectName("shipinzhanshi")

        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(130, 60, 75, 24))
        self.openButton.setObjectName("openButton")
        self.openButton.clicked.connect(self.open_file)  # 实现跳转的信号语句
        # self.timer = QTimer()
        # self.timer.timeout.connect(self.update_frame)

        self.cap = None

        self.yundongxuanze = QtWidgets.QComboBox(self.centralwidget)
        self.yundongxuanze.setGeometry(QtCore.QRect(230, 60, 201, 21))
        self.yundongxuanze.setObjectName("yundongxuanze")
        self.yundongxuanze.addItem("")
        self.yundongxuanze.addItem("")
        self.jishu_2 = QtWidgets.QPushButton(self.centralwidget)
        self.jishu_2.setGeometry(QtCore.QRect(480, 60, 75, 24))
        self.jishu_2.setObjectName("jishu_2")
        self.jishu = QtWidgets.QTextEdit(self.centralwidget)
        self.jishu.setGeometry(QtCore.QRect(210, 460, 71, 41))
        self.jishu.setObjectName("jishu")
        self.zongji = QtWidgets.QLabel(self.centralwidget)
        self.zongji.setGeometry(QtCore.QRect(140, 460, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zongji.setFont(font)
        self.zongji.setObjectName("zongji")
        self.jiazaishipin = QtWidgets.QProgressBar(self.centralwidget)
        self.jiazaishipin.setGeometry(QtCore.QRect(100, 420, 601, 21))
        self.jiazaishipin.setProperty("value", 24)
        self.jiazaishipin.setObjectName("jiazaishipin")
        self.hege_num = QtWidgets.QLabel(self.centralwidget)
        self.hege_num.setGeometry(QtCore.QRect(320, 470, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hege_num.setFont(font)
        self.hege_num.setObjectName("hege_num")
        self.hegeshu = QtWidgets.QTextEdit(self.centralwidget)
        self.hegeshu.setGeometry(QtCore.QRect(410, 460, 71, 41))
        self.hegeshu.setObjectName("hegeshu")
        self.buhege_num = QtWidgets.QLabel(self.centralwidget)
        self.buhege_num.setGeometry(QtCore.QRect(500, 470, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buhege_num.setFont(font)
        self.buhege_num.setObjectName("buhege_num")
        self.buhegeshu = QtWidgets.QTextEdit(self.centralwidget)
        self.buhegeshu.setGeometry(QtCore.QRect(580, 460, 71, 41))
        self.buhegeshu.setObjectName("buhegeshu")
        self.zongfen_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.zongfen_2.setGeometry(QtCore.QRect(310, 510, 181, 41))
        self.zongfen_2.setObjectName("zongfen_2")
        self.zongfennum = QtWidgets.QLabel(self.centralwidget)
        self.zongfennum.setGeometry(QtCore.QRect(230, 510, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zongfennum.setFont(font)
        self.zongfennum.setObjectName("zongfennum")
        self.baocun = QtWidgets.QPushButton(self.centralwidget)
        self.baocun.setGeometry(QtCore.QRect(590, 60, 75, 24))
        self.baocun.setObjectName("baocun")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-60, 10, 951, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(60, 410, 41, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.button_start.setFont(font)
        self.button_start.setStyleSheet("border-image: url(:/background/icons/begin.png);")
        self.button_start.setText("")
        self.button_start.setObjectName("button_start")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(690, 410, 31, 31))
        self.button_stop.setStyleSheet("border-image: url(:/background/icons/stop.png);")
        self.button_stop.setText("")
        self.button_stop.setObjectName("button_stop")

        title.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(title)
        self.statusbar.setObjectName("statusbar")
        title.setStatusBar(self.statusbar)

        self.retranslateUi(title)
        QtCore.QMetaObject.connectSlotsByName(title)

    def retranslateUi(self, title):
        _translate = QtCore.QCoreApplication.translate
        title.setWindowTitle(_translate("title", "MainWindow"))
        self.openButton.setText(_translate("title", "打开"))
        self.yundongxuanze.setItemText(0, _translate("title", "仰卧起坐"))
        self.yundongxuanze.setItemText(1, _translate("title", "引体向上"))
        self.jishu_2.setText(_translate("title", "计数"))
        self.zongji.setText(_translate("title", "总计："))
        self.hege_num.setText(_translate("title", "合格数量："))
        self.buhege_num.setText(_translate("title", "不合格数量："))
        self.zongfennum.setText(_translate("title", "总分："))
        self.baocun.setText(_translate("title", "保存"))
        self.label.setText(_translate("title", "运动姿态识别"))

    def open_file(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        self.video_path, _ = QFileDialog.getOpenFileName(self, "Open Video", "", "Video Files (*.mp4 *.avi *.mkv)",
                                                         options=options)

        if self.video_path:
            self.show_video()

    def show_video(self):
        cap = cv2.VideoCapture(self.video_path)
        frame_width = self.shipinzhanshi.width()
        frame_height = self.shipinzhanshi.height()

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            # Convert the frame to RGB format
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            # Resize the frame to fit QLabel
            frame_resized = cv2.resize(frame_rgb, (frame_width, frame_height))

            # Convert the frame to QImage
            img = QtGui.QImage(frame_resized.data, frame_resized.shape[1], frame_resized.shape[0],
                               frame_resized.strides[0], QtGui.QImage.Format_RGB888)
            # Set the QImage as QLabel's pixmap
            self.shipinzhanshi.setPixmap(QtGui.QPixmap.fromImage(img))
            # Update the QLabel
            self.shipinzhanshi.repaint()

            # Wait for 25 milliseconds and handle events
            cv2.waitKey(25)
            QtWidgets.QApplication.processEvents()

        cap.release()

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_title()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置

    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
